name: Daily Feed Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Debug structure
      run: ls -R

    - name: Install dependencies
      run: npm install

    - name: Run script
      run: node feeder-update.js
